spring:
  application:
    name: sistema-mr
    
  
  ai:
    vectorstore:
      neo4j:
        database-name: neo4j
        index-name: chat-memory-index
    
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        embedding:
          api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.1-flash-lite
          temperature: 0.3
          google-search-retrieval: false
          include-thoughts: false
          thinking-level: LOW
   
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: neo4j
      password: ${PASSWD_NEO4J}
  